#Spring Common Parameters
server.port=8081
logging.level.root=info

#User Custom Parameters
browser=chrome
headless=false
explicitTimeout=5000
grid-url=null
grid-token=null
grid=false
baseUrl=https://portal.bennettonline.com/
loginUrl=https://portal.bennettonline.com/auth/login
OID_TOKEN_KEY=oidc.user:https://https://portal.bennettonline.com/auth:4FnVvfLW6PzOvmsFbAgEdZKDraRZljhWHUFCEAKFw-Y
